name: "OpenAPI Diff Action"
author: "Dmitry Vasiliev"
description: "A GitHub Action to identify differences between OpenAPI specifications. It uses OpenAPITools/openapi-diff."
branding:
  icon: 'check-square'
  color: 'blue'

inputs:
  old-spec:
    description: "Old specification filename"
    required: true
  new-spec:
    description: "New specification filename"
    required: true
  header:
    description: "Use given header for authorization"
    required: false
    default: ""
  query:
    description: "Use query param for authorization"
    required: false
    default: ""
  markdown:
    description: "Export diff as markdown in given file"
    required: false
    default: ".tmp/markdown"
  text:
    description: "Export diff as text in given file"
    required: false
    default: '.tmp/text'
  fail-on:
    description: "Fail if API changed but is backward compatible ('changed' value) or changes broke backward compatibility ('incompatible' value)"
    required: false
    default: ""

outputs:
  state:
    description: "Output diff state: no_changes, incompatible, compatible"
    value: ${{steps.state.outputs.compare_state}}

runs:
  using: composite
  steps:
    - name: "Run openapi-diff tool"
      run: |
        docker run -v "$(pwd):/specs" --rm openapitools/openapi-diff:2.0.1 \
          /specs/${{inputs.old-spec}} \
          /specs/${{inputs.new-spec}} \
          `if [[ ${{inputs.header}} != '' ]]; then --header ${{inputs.header}}; fi` \
          `if [[ ${{inputs.query}} != '' ]]; then --query ${{inputs.query}}; fi` \
          `if [[ ${{inputs.fail-on}} != '' ]]; then --fail-on-${{inputs.fail-on}}; fi` \
          --markdown /specs/${{inputs.markdown}} \
          --text /specs/${{inputs.text}}
      shell: bash
    - name: "Check file existence"
      id: check_files
      uses: andstor/file-existence-action@v3
      with:
        files: ".tmp"
    - name: "Post: Change folder own group"
      if: steps.check_files.outputs.files_exists == 'true'
      run: sudo chown -R $USER:$USER .tmp
      shell: bash
    - name: "Post: Remove .tmp directory"
      if: steps.check_files.outputs.files_exists == 'true'
      run: rm -fr .tmp
      shell: bash